added  a release pipeline
cdevents/sdk-rust pull request #17
Opened 2024-02-15 14:41 UTC by rjtch

added a release pipeline wip

2024-02-15 17:42 UTC, davidB commented
IMHO, we don't need cargo-dist as we provide a lib and not an executable binary.

2024-02-15 22:02 UTC, rjtch commented
> IMHO, we don't need cargo-dist as we provide a lib and not an executable binary.

Yes you are wright i am working on it!

2024-02-25 18:21 UTC, davidB requested changes

2024-02-25 18:21 UTC, davidB commented on .github/workflows/release.yml
> +          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
Currently we don't need to trigger other workflow (I guess), so the default (`${[ secrets.GITHUB_TOKEN }}` is enough.
So the secrets `RELEASE_PLZ_TOKEN` could be removed

2024-02-25 18:21 UTC, davidB commented on .github/workflows/release.yml
> +  packages: write
I think the permission `packages` is useless, we don't use the packages from github.
But the following permission is missing

```
pull-requests: write
```

To allow release-plz to create and update PR

2024-02-25 18:21 UTC, davidB commented on .github/workflows/release.yml
> +name: Release
I prefer when the name is aligned with the filename (same case)

2024-02-25 18:21 UTC, davidB commented on .github/workflows/release.yml
> +          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
could also be remove, and used the default

2024-02-25 18:21 UTC, davidB commented on Cargo.toml
all the section `[workspace.metadata.release]` can be removed if we switch to `release-plz`

2024-02-25 18:21 UTC, davidB commented on cdevents-sdk/src/uri.rs
> -}
Why do you remove this section?

`impl Display` only replace `impl ToString`, but not the conversion from a String

2024-02-25 18:21 UTC, davidB commented on cdevents-sdk/src/uri_reference.rs
> -}
Why do you remove this section?

`impl Display` only replace `impl ToString`, but not the conversion from a String

2024-02-25 18:21 UTC, davidB commented on cdevents-sdk/src/uri_reference.rs
> +    type Strategy = proptest::strategy::BoxedStrategy<Self>;
Why moving this `type` at the end?

2024-02-25 18:21 UTC, davidB commented on generator/Cargo.toml
> +handlebars_misc_helpers = { version = "0.15", default-features = false, features = ["string", "json"] }
Which toml formatter do you use?

2024-02-25 18:21 UTC, davidB commented on tools/cliff/cliff.toml
releaze-plz comes with its own configuration for cliff. I guess it's better to use the default configuration. Or to use the release-plz configuration to setup cliff?

Side question, moving all config into an other place than the default one create clear root directory, but need to customize call of tools,... and bit of confusion (IMHO). Why do you made this choice?

2024-02-25 20:05 UTC, davidB commented on .github/workflows/release.yml
> +          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
To be more explicit, we need to specify a token if we want that change on the repo (e.g., tagging) made by the job to trigger another other GitHub workflow.

An alternative to a PAT is to create a ssh-key (registered as secret + deploy key in the repository's settings). I use this approach instead of a PAT attached to a user at work.

2024-03-01 17:24 UTC, rjtch commented on cdevents-sdk/src/uri.rs
> -}
clippy was complaining about that and the suggestion was to use Display instead _https://github.com/cdevents/sdk-rust/actions/runs/7932241774/job/21658258032_ . here is the explaination _https://rust-lang.github.io/rust-clippy/master/index.html#/to_string_trait_impl_

2024-03-02 14:45 UTC, davidB requested changes

2024-03-02 14:45 UTC, davidB commented on .github/workflows/release.yml
> +pull-requests: write
```suggestion
permisssions:
  contents: read
  pull-requests: write
```

2024-03-02 14:49 UTC, davidB commented on cdevents-sdk/src/uri.rs
> -}
The clippy suggestion is only about `ToString`, not about `TryFrom<String>`

2024-03-02 18:09 UTC, davidB commented
@rjtch Please don't use the nightly toolchain for CI & linting, our target is stable. And it's better if version used by ci is aligned with what is defined into the project to allow developer to reproduce locally ci,... (building / linting against nightly is informative, optional and not a blocker).

2024-03-03 12:43 UTC, davidB commented
I didn't have the failure in the ci/tests. The issue is in the spec IMHO (URL field of type `string` instead of type `uri`), I included a workaround the PR #19.

2024-03-03 12:44 UTC, davidB approved these changes

2024-03-03 15:04 UTC, davidB commented
After the merge of this PR, I'll rebase PR #19, so CI should become green :crossed_fingers:

2024-03-03 16:58 UTC, merged